### ISSUE TITLE
How to train the model on other datasets with any size?

### ISSUE THREAD

**Issue by ysc703** [BichenWuUCB/squeezeDet#1]
Hi
   I want to tain the model with other dataset, but with different size with KITTI dataset.
   I changed the mc.IMAGE_WIDTH and mc.IMAGE_HEIGHT to my dataset, but they can't suit to the pretrained_model squeezenet_v1.0_SR_0.750.pkl and got error : 
   "ValueError: Cannot reshape a tensor with 47196 elements to shape [1,15048,3]....".
   
     Thanks for your help!

**Comment by BichenWuUCB** [comment]
Thanks for your interest in my work.

To change image resolution, you also need to change grid size in the config file, which can be found at this line: https://github.com/BichenWuUCB/squeezeDet/blob/master/src/config/kitti_squeezeDetPlus_config.py#L46

Current implementation is not smart enough to figure out grid size automatically according to image resolution, so you may need to manually compute it and then change the config file accordingly.

**Comment by ysc703** [comment]
Thanks a lot!  I will try it.
