### ISSUE TITLE
How to select an appropriate number of anchors

### ISSUE THREAD

**Issue by Lisandro79** [BichenWuUCB/squeezeDet#10]
Hi @BichenWuUCB, 

I am trying to run SqueezeDet with my dataset. My images have a resolution of 720 x 405 pixels and the there are 15 classes of objects in the dataset.

I am able to run the demo and train the KITTI dataset with SqueezeDet, but when I use my images I get a problem with the dimension of the tensor in the softmax layer.

This is my setup file:

```
# Model configuration for pascal dataset

import numpy as np

from config import base_model_config


def my_squeezeDetPlus_config():
    "Specify the parameters to tune below."

    mc = base_model_config('my_model')

    mc.IMAGE_WIDTH = 720  # 720  # 1242
    mc.IMAGE_HEIGHT = 405  # 405  # 375
    mc.BATCH_SIZE = 20

    mc.WEIGHT_DECAY = 0.0001
    mc.LEARNING_RATE = 0.01
    mc.DECAY_STEPS = 10000
    mc.MAX_GRAD_NORM = 1.0
    mc.MOMENTUM = 0.9
    mc.LR_DECAY_FACTOR = 0.5

    mc.LOSS_COEF_BBOX = 5.0
    mc.LOSS_COEF_CONF_POS = 75.0
    mc.LOSS_COEF_CONF_NEG = 100.0
    mc.LOSS_COEF_CLASS = 1.0

    mc.PLOT_PROB_THRESH = 0.4
    mc.NMS_THRESH = 0.4
    mc.PROB_THRESH = 0.005
    mc.TOP_N_DETECTION = 64

    mc.DATA_AUGMENTATION = True
    mc.DRIFT_X = 150
    mc.DRIFT_Y = 100
    mc.EXCLUDE_HARD_EXAMPLES = False

    mc.ANCHOR_BOX = set_anchors(mc)
    mc.ANCHORS = len(mc.ANCHOR_BOX)
    mc.ANCHOR_PER_GRID = 9

    return mc


def set_anchors(mc):
    (H, W, B) = (22, 76, 9)  # (22, 42, 9)
    anchor_shapes = np.reshape([np.array([
        [36., 37.],
        [366., 174.],
        [115., 59.],
        [162., 87.],
        [38., 90.],
        [258., 173.],
        [224., 108.],
        [78., 170.],
        [72., 43.],
        ])] * H * W, (H, W, B, 2))
    center_x = \
        np.reshape(np.transpose(np.reshape(np.array([np.arange(1, W
                   + 1) * float(mc.IMAGE_WIDTH) / (W + 1)] * H * B),
                   (B, H, W)), (1, 2, 0)), (H, W, B, 1))
    center_y = \
        np.reshape(np.transpose(np.reshape(np.array([np.arange(1, H
                   + 1) * float(mc.IMAGE_HEIGHT) / (H + 1)] * W * B),
                   (B, W, H)), (2, 1, 0)), (H, W, B, 1))
    anchors = np.reshape(np.concatenate((center_x, center_y,
                         anchor_shapes), axis=3), (-1, 4))

    return anchors
```

When I run the scripts I get this error

```
File "/home/my_dataset/squeezeDet/src/nn_skeleton.py", line 135, in _add_interpretation_graph

ValueError: Cannot reshape a tensor with 2786400 elements to shape [20,15048,15] (4514400 elements) for 'interpret_output/pred_class_probs' (op: 'Reshape') with input shapes: [185760,15], [3].
```

I assume this is a problem with the number of anchors (15048) that I am using. The default number of anchors does not seem appropriate for my dataset but I cannot understand how to set those values correctly.

The parameters H, W and B are set by default to "(22, 76, 9)" inside the function "set_anchors" (in the setup file above). How were these values selected? Is there a formula to calculate the appropriate number of batch, anchors and classes (so that they match with the tensor dimension) given an image resolution? 

Thanks a lot

**Comment by Lisandro79** [comment]
Following the previous posts on the topic I solved this issue using

```
mc.IMAGE_WIDTH = 720  
mc.IMAGE_HEIGHT = 405 
```

and

`(H, W, B) = (24, 43, 9) `

**Comment by vhtrivedi** [comment]
@Lisandro79 How did you fix H W B?

**Comment by Lisandro79** [comment]
Just set a breakpoint in that line and played around with the numbers until I got the exact size of the vector that was complaining in the error. It was more an art than science.

For my image size of 720x405, H=24 and W=43 resulted in the tensor of the same dimension as "interpret_output/pred_class_probs".

Hope this helps
