### ISSUE TITLE
Deploying squeezeDet on mobile

### ISSUE THREAD

**Issue by redhood95** [BichenWuUCB/squeezeDet#123]
how can we convert the trained squeezeDet model to tflite for deployment as tflite does'nt seem to have direct compatibility for detector layers?

**Comment by acmaheri** [comment]
You need to reimplemented object detector part which is to some extent easier than trying to get this implementation working on mobile.

**Comment by redhood95** [comment]
okay thanks

**Comment by acmaheri** [comment]
you can check this [out](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjp0u2sqPriAhXQbFAKHep5B3kQFjABegQIBhAC&url=http%3A%2F%2Fcs231n.stanford.edu%2Freports%2F2017%2Fposters%2F627.pdf&usg=AOvVaw35fUCTXPZOG9zkE7eWLiTS)
