### ISSUE TITLE
Transfer learning performance

### ISSUE THREAD

**Issue by amrit110** [BichenWuUCB/squeezeDet#13]
Hi, I tried inference of the pretrained models as well as the ones I trained using your code on datasets other than KITTI. For example cityscapes was one of them, and the performance was extremely depreciated. Any reason for this? Typically, it shouldn't be that bad, perhaps it is overfitting? KITTI data contains verly low variation, but I still expected decent performance on cityscpaes? Any ideas or perhaps something I might be doing wrong?

**Comment by BichenWuUCB** [comment]
@amrit110 Well, there can be a lot of reasons. If you could point me to your repository and share more details of your training procedure, that's going to be helpful for us to locate the problems.

**Comment by amrit110** [comment]
sorry false alarm. Ok so, i used a model trained on KITTI but changed the config file to use demo.py on cityscapes images. When I said overfitting, that was not really what i meant because a lightweight model like yours should be even less prone to overfitting. I was concerned that the model performed well only on KITTI images (camera config and conditions). So, then i realised that the image size i was using from cityscapes was the original (2048 x 1024) which is why i got bad performance. I rescaled it to something closer to the training set (KITTI) and then i get expected performance. Now, I am trying to actually train it on cityscapes. great work, love the low inference time. if i manage to train on cityscapes successfully, ill share the results.
![out_stuttgart_00_000000_000009_leftimg8bit](https://cloud.githubusercontent.com/assets/8986523/23699173/78bf365c-03ee-11e7-9349-1c2a1e3e9526.png)

**Comment by BichenWuUCB** [comment]
@amrit110 Great, looking forward to your cityscape result.
