### ISSUE TITLE
dataset for the result on paper

### ISSUE THREAD

**Issue by ByoenghakYim** [BichenWuUCB/squeezeDet#18]
I wonder what data you used for the result on your paper. Is that randomly split validation data from 7481 training data or 7518 of test benchmark data?
Thanks

**Comment by BichenWuUCB** [comment]
@ByoenghakYim As described in our paper, that result is on a validation dataset that is randomly selected from KITTI's training dataset.

**Comment by twangnh** [comment]
@BichenWuUCB seems result on validation and official Test benchmark differs greatly, I randomly split the training set and run the model(squeezedet), after some tune I got close to paper result, which is 
![validation-result](https://user-images.githubusercontent.com/18298163/39670929-97250e22-5141-11e8-956e-08613d189da0.png)
but same model with same hyperparams tested on official Test Benchmark only got:
![kitti-eval-result](https://user-images.githubusercontent.com/18298163/39670932-a0c2fc5a-5141-11e8-98da-0cf74fd2d2d5.png)
but the result reported on table compares with methods test on official test test, can you explain where is missed here? your feedback is really expected, thank you!

**Comment by eypros** [comment]
@twangnh can you please clarify what exactly what your tuning? I mean did you use different parameters than the one mentioned in the paper? Did you train longer? Something else?
