### ISSUE TITLE
Running out of memory during simultaneous training and evaluation 

### ISSUE THREAD

**Issue by stephencwelch** [BichenWuUCB/squeezeDet#2]
While training on the KITTI data set, I seem to run out of memory when I try to run both evaluation scripts simultaneously (scripts/eval_train.sh and scripts/eval_val.sh):

`Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuCtxCreate: CUDA_ERROR_OUT_OF_MEMORY;`

Is this just a matter of me needing to adjust my batch size to allow all 3 processes enough memory to simultaneously run? I have ~24GB of VRAM across 2 Titan XPs - since this implementation does not seem setup to support multiple GPUs, I've tried using GPU 0 for training and GPU 1 for running the two evaluation scripts, I still run out of memory though. 

Thanks!

**Comment by BichenWuUCB** [comment]
Hi,

When you launch a train or eval thread, tensorflow by default accesses all the GPUs that is visible to it. To compleletly seperate them, you need to set the evironment variable `CUDA_VISIBLE_DEVICES` to be the GPU you want to use for each task. Say, in session-1, set visible device to 0, then launch training. In session-2, set visible device to 1, and launch eval. In my experiment, I assign each train/eval_train/eval_val to a different GPU instance.  

Hope that helps.
