### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by yimintsai** [BichenWuUCB/squeezeDet#24]
Hi, is it possible to train with KITTI database from scratch (without pre-trained model). For example, set `cfg.LOAD_PRETRAINED_MODEL` to `False`? It seems that it is not easy to converge?

**Comment by BichenWuUCB** [comment]
@yimintsai You can set the flag to false and it should use randomly-initialized parameters. But just like you said, training from scratch on such a small dataset usually encounter problems and convergence is one of them.
