### ISSUE TITLE
can not download the pertrained model

### ISSUE THREAD

**Issue by zhyj3038** [BichenWuUCB/squeezeDet#3]
thanks very much for your work, i can not download your pretrained model , because i am in china~~. can you offer an alternative  place?, such as "baidu net disk"

**Comment by samlong-yang** [comment]
I cannot download the model either....

**Comment by ChaunceyWang** [comment]
@zhyj3038 @samlong-yang ,Hi,friends , I just downloaded the models by this way: firstly, you save the files to your own Dropbox, then you can download them from your Dropbox. You can try it!

**Comment by samlong-yang** [comment]
@zhyj3038 , I've downloaded the models and uploaded them on the Baidu net disk, maybe you can download the models from here
URL：http://pan.baidu.com/s/1nuVFMzR 
PW：424s

**Comment by zhyj3038** [comment]
@samlong-yang     Thanks very much，I have download the model ^^!

**Comment by BichenWuUCB** [comment]
@zhyj3038 Thanks for doing that!
