### ISSUE TITLE
Training with custom data shape

### ISSUE THREAD

**Issue by milan0092** [BichenWuUCB/squeezeDet#30]
Hi,

Is it possible to train squeezeDet on custom data without resizing to the 1242*375 KITTI format?
In kitti_squeezedet_config.py the image width and height can be changed, but that seems to conflict with set_anchors.

Thanks!

**Comment by AndreaPisoni** [comment]
Just change the set_anchor modifiers to make the shapes match. There is
already a closed issue about that if you take a look at the previous
questions.

**Comment by milan0092** [comment]
My bad! Thanks :)
