### ISSUE TITLE
Unsafe, safe_exp function

### ISSUE THREAD

**Issue by Timen** [BichenWuUCB/squeezeDet#36]
The function safe_exp

        lin_region = tf.to_float(w > thresh)

        lin_out = slope*(w - thresh + 1.)

        exp_out = tf.exp(w)

        out = lin_region*lin_out + (1.-lin_region)*exp_out

 
Solves the exploding exponent problem, but is not safe. As exp_out is still exp(w) and can thus still become NaN, which then makes the variable out equal to NaN because multiplying a NaN by 0 still returns NaN and adding by NaN also returns NaN.

I propose adding a select, to not feed w to exp when the function is in the linear region like this: 
   
    lin_region_bool = tf.greater(w , thresh)
    lin_region = tf.to_float(lin_region_bool)
    lin_out = tf.multiply(lin_region,tf.multiply(slope,tf.add(tf.subtract(w , thresh), float(1.0))))

    exp_out_safe = tf.exp(tf.where(lin_region_bool,tf.multiply(tf.ones_like(w),thresh),w))

    exp_out = tf.multiply(tf.subtract(float(1.0),lin_region),exp_out_safe)

    out = tf.add(lin_out,exp_out)

**Comment by BichenWuUCB** [comment]
Ahh, yes, it definitely makes sense. Would you file a pull request to fix this?

**Comment by BichenWuUCB** [comment]
@Timen Nevermind, it's fixed.
