### ISSUE TITLE
Using SqueezeDet with Tensorflow C++ API

### ISSUE THREAD

**Issue by July-Morning** [BichenWuUCB/squeezeDet#37]
First of all, thanks a lot for sharing your code. SqueezeDet is really great.

I managed to train it on my own dataset and everything was good while I was using it in Python. I am not using GPU and detection takes 60-80ms for the 400x225 image on my CPU. 
However, when I freezed the graph and loaded it in C++ code, session->run began to take 480-500ms on the same data. Any idea why it is so?
I have set optimization flag --config=opt when building with bazel and I have tried setting all the flags manually, it did not help. I am a new in tensorflow, and there is not much documentation on C++ Api issues, so I thought someone here could tell me what the reason of such a slow down for squeezeDet is. Any help would be highly appreciated.

**Comment by BichenWuUCB** [comment]
Not much experience in C++ API. Maybe you have seen this before but here is a [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/3471) discussing this.

**Comment by July-Morning** [comment]
Thank you for the response, @BichenWuUCB!
Yes, I have seen that issue and have already set all flags, but significant gap still exists. It seems to me a tensorflow-related problem, so I will try to ask for help there.
