### ISSUE TITLE
On train data annotation 

### ISSUE THREAD

**Issue by ChaunceyWang** [BichenWuUCB/squeezeDet#39]
For one train image, do I need to annotate all objects in the image during training.
for example , an image for pedestrian detection is : 
![qq 20170507184124](https://cloud.githubusercontent.com/assets/17997053/25780272/80edccba-3357-11e7-9e77-815afb321320.png)
If I only annotate the left pedestrian(there are other pedestrians), is it good for net training?

In my option , there are no explicit positive and negative samples . Does that mean : The other area is negatives except positives given by ground truth in one image? So I need to annotate all goals?  I am not sure.

**Comment by BichenWuUCB** [comment]
It depends on your training protocol. But if it's SqueezeDet's training protocol, yes, you need to annotate all targets by the same standard (distance, size, occlusion) or otherwise, it's going to cause confusion to the network training.

**Comment by ChaunceyWang** [comment]
Get that, thank you!
