### ISSUE TITLE
Training on own dataset: imdb.py IndexError: too many indices for array

### ISSUE THREAD

**Issue by mistiansen** [BichenWuUCB/squeezeDet#58]
Hello,
I am attempting to train squeezeDet on my own images. They are size 1600x1200. I set the grid H, W to be roughly 1/16 of the size of the H, W respectively (75 and 100) as recommended. I also adjusted the batch size because batch size of 20 was not fitting in memory. 
The training runs smoothly for up to 350 iterations but then produces the following error:

  ****File "/p/home/squeezeDet/src/dataset/imdb.py", line 157, in read_batch
    max_drift_x = min(gt_bbox[:, 0] - gt_bbox[:, 2]/2.0+1)
IndexError: too many indices for array**

Does anyone have any advice or knowledge of what may be causing this?
The full error output is below.

Traceback (most recent call last):
  File "./src/train.py", line 345, in <module>
    tf.app.run()
  File "/p/work2/projects/ryat/modules/tensorflow/1.0.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./src/train.py", line 341, in main
    train()
  File "./src/train.py", line 270, in train
    coord.join(threads)
  File "/p/work2/projects/ryat/modules/tensorflow/1.0.0/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "./src/train.py", line 229, in _enqueue
    feed_dict, _, _, _ = _load_data()
  File "./src/train.py", line 166, in _load_data
    bbox_per_batch = imdb.read_batch()
  ****File "/p/home/squeezeDet/src/dataset/imdb.py", line 157, in read_batch
    max_drift_x = min(gt_bbox[:, 0] - gt_bbox[:, 2]/2.0+1)
IndexError: too many indices for array**

**Comment by mrlzla** [comment]
That's because you can have images without objects.
I am trying to train the model on my own dataset too. After a while I get an error that my model diverges. Do you have the same error?

**Comment by mistiansen** [comment]
Yes I realized one of my labels had no content. Thanks.
I haven't gotten the same error yet but I'll let you know if I do

**Comment by eleboss** [comment]
@mistiansen check the class name of the your lable file and the class name in kitti.
I meet the same problem and fixed by modified the config.py

**Comment by hoonkai** [comment]
@mrlzla Do you mean you can have images without objects or you can't have images without objects?

**Comment by acmaheri** [comment]
Has someone already sort this out, on how one can pass the custom dataset onto squeezedDet nets?
