### ISSUE TITLE
Is there a caffe implementation plan?

### ISSUE THREAD

**Issue by rainsoulsrx** [BichenWuUCB/squeezeDet#6]
Hi Bichen, I have train the squeezeDet using data of my own, it turn out to be effective. But I want to train it using caffe for caffe is much more familiar for me. So is an caffe implementation possiable? Because without a pretrained caffemodel to finetune with, may be the net could not converge very well.
Waiting for you reply, thanks~~

**Comment by BichenWuUCB** [comment]
@rainsoulsrx We don't plan to re-implement it in caffe. But if anyone else is willing to do this, that would be great.
