### ISSUE TITLE
Can squeezeDet handle arbitrary image resolution?

### ISSUE THREAD

**Issue by mubastan** [BichenWuUCB/squeezeDet#66]
It seems the image resolution is fixed in the configuration files. Changing the image resolution breaks the system with the pretrained models (leads to error in nn_skeleton.py", line 159, in _add_interpretation_graph).

So, my conclusion is that image resolution has to be fixed and for each resolution, the network needs to be modified(???). Moreover, it cannot handle arbitrary resolutions (big disadvantage, but can still be useful for fixed size datasets or videos).
Is this conclusion correct?

**Comment by AndreaPisoni** [comment]
Just resize the image before feeding it to the network?

**Comment by mubastan** [comment]
This seems to be the easiest solution, but it is not practical for most datasets, especially when the aspect ratios are different.

**Comment by AndreaPisoni** [comment]
You can pad the images so that they all get to a target aspect ratio.
