### ISSUE TITLE
About more classes

### ISSUE THREAD

**Issue by rainsoulsrx** [BichenWuUCB/squeezeDet#7]
Hi Bichen, It's me again~~
I want to train the squeezeDet to detect more classes, that to say, not only 'car', 'pedestrian', 'cyclist', I need to prepare the datasets and change the CLASS_NAMES in the config.py. Any other changes need to do? Do I need to change the parameter of the net?
Waiting for your reply~~

**Comment by BichenWuUCB** [comment]
One more thing you need to change is the last layer's channel size. Recall that in the _ConvDet_ layer in squeezeDet, the output channel size is `K(C+5)` where `K` is the number of anchors, `C` is the number of classes, and 5 is 1 confidence score + 4 coordinates. 

There might be something else that you need to change, but the best way to figure that out is to play with the code. 

Good luck.
