### ISSUE TITLE
Suggestions to Train on My Own Data?

### ISSUE THREAD

**Issue by zesoft23** [BichenWuUCB/squeezeDet#8]
Hi @BichenWuUCB 

So I'm looking into using squeezeDet  on my own data that's not in KITTI format. Do you have any suggestions on how to go about this?

**Comment by BichenWuUCB** [comment]
Thanks for your interest. 

Basically I suggest two options:

You can try to convert the data into the KITTI format, including image files, annotations, index files, etc. Then, you don't have to change SqueezeDet code too much to make it work. 

Or, you can change the data processing code in SqueezeDet. A brief walk-through for this part of the code: 
  - The root class of image database is defined [here](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/dataset/imdb.py). If you want to know how an image (together with annotation) is fed into an NN, look at this [funcion](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/dataset/imdb.py#L99). 
  - For specific dataset, refer to [file](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/dataset/kitti.py). It defines how to load/preprocess KITTI dataset.  

Ideally, you can start with these two files. Let me know if you have more questions.

Bichen
