### ISSUE TITLE
Different equation compared to paper?

### ISSUE THREAD

**Issue by shuuki4** [BichenWuUCB/squeezeDet#9]
Hi, @BichenWuUCB. I'm currently playing with your squeezeDet code, but I found some suspicious part in your code, so it would be grateful if you check if this is wrong or not.

In ``read_batch`` function in ``/dataset/imdb.py``, conversion code of ground truth bounding box into delta is
```
delta[0] = (box_cx - mc.ANCHOR_BOX[aidx][0])/box_w
delta[1] = (box_cy - mc.ANCHOR_BOX[aidx][1])/box_h
delta[2] = np.log(box_w/mc.ANCHOR_BOX[aidx][2])
delta[3] = np.log(box_h/mc.ANCHOR_BOX[aidx][3])
```
Isn't it correct to divide delta[0] and delta[1] with ``mc.ANCHOR_BOX[aidx][2]``, ``mc.ANCHOR_BOX[aidx][3]`` respectively? Equation (3) in the paper divides it with anchor box width/height, and I personally think that dividing by fixed value (anchor box width/height) is more stable normalization.

Thanks!

**Comment by BichenWuUCB** [comment]
@shuuki4 thanks for your question. I guess your question is already answered in #4 . Equation (3) in the paper should be fixed, the code implementation is correct. Sorry for the confusion.

**Comment by shuuki4** [comment]
If the code implementation is correct, I think this part of the code (Line 170 of ``nn_skeleton.py``) should be changed:
```
        box_center_x = tf.identity(
            anchor_x + delta_x * anchor_w, name='bbox_cx')
        box_center_y = tf.identity(
            anchor_y + delta_y * anchor_h, name='bbox_cy')
        box_width = tf.identity(
            anchor_w * util.safe_exp(delta_w, mc.EXP_THRESH),
            name='bbox_width')
        box_height = tf.identity(
            anchor_h * util.safe_exp(delta_h, mc.EXP_THRESH),
            name='bbox_height')
```

Since delta is divided by ground truth bboxes' width and height, gt boxes' width and height should be used when stretching box_center_x and box_center_y. However, this code uses anchor_w and anchor_h to rescale the box center. Therefore, if the code implementation is correct, this code should also be changed to use ground truth box width/height. Even if this information does not directly affect the learning process, it affects final prediction for raw bounding box coordinates and also affect visualizations, so I think this code should be fixed.

One more concern is that ``eval.py`` uses this code (``model.det_boxes``) for final bounding box prediction. Since there is no ground truth for test data split, it is impossible to rescale delta into real coordinates.  Therefore, I think it is necessary to normalize delta with anchor box width/heights.
